/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#75777d",
        "primary-fixed-dim": "#b9c7e0",
        "secondary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed": "#281901",
        "tertiary-fixed-dim": "#dfc299",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed-variant": "#574424",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "primary-container": "#334155",
        "surface-container": "#eceef0",
        "tertiary-fixed": "#fcdeb3",
        "on-primary-fixed-variant": "#3a485c",
        "error-container": "#ffdad6",
        primary: "#1d2b3e",
        "on-primary-fixed": "#0d1c2f",
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
        surface: "#f7f9fb",
        "on-secondary-fixed-variant": "#38485d",
        "on-error": "#ffffff",
        "secondary-container": "#d0e1fb",
        "on-primary-container": "#9eadc5",
        "on-tertiary": "#ffffff",
        "surface-tint": "#515f74",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed": "#d5e3fd",
        "inverse-on-surface": "#eff1f3",
        "surface-dim": "#d8dadc",
        "on-surface-variant": "#44474c",
        "on-secondary-fixed": "#0b1c30",
        secondary: "#505f76",
        "inverse-primary": "#b9c7e0",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#54647a",
        "surface-variant": "#e0e3e5",
        "on-tertiary-container": "#c3a881",
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#c5c6cd",
        background: "#f7f9fb",
        "tertiary-container": "#503d1e",
        tertiary: "#38270a"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "touch-target": "44px",
        "base-unit": "4px",
        "table-row-height": "3.5rem",
        "container-padding": "1rem",
        "stack-gap": "0.75rem"
      },
      fontFamily: {
        "display-sm": ["Inter"],
        "label-caps": ["Inter"],
        "data-tabular": ["Inter"],
        "body-base": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "display-sm": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "data-tabular": ["15px", { "lineHeight": "20px", "fontWeight": "500" }],
        "body-base": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
